Feature/listen to fastclock
slashdev/loconet_domotica pull request #10
Opened 2017-02-19 17:22 UTC by jmvdwerf

2017-03-17 16:25 UTC, fuegas requested changes

2017-03-17 16:25 UTC, fuegas commented on src/domotica/domotica_fastclock.c
> +  uint16_t timestamp;
Kun je uitleggen hoe deze variabele eruit ziet? Want eigenlijk is het geen timestamp als `1604` betekent vier minuten over vier in de middag. Dan is het eerder een `timepattern`.

2017-03-17 16:25 UTC, fuegas commented on src/domotica/domotica_fastclock.c
> +    // If last_timestamp is smaller than the current_time, we just check
Als je hier begint met de controle of `timestamp` gelijk is aan `0xFF` dan hoef je hier geen rekening mee te houden in je vergelijking hieronder.

2017-04-16 13:44 UTC, jmvdwerf commented on src/domotica/domotica_fastclock.c
> +  uint16_t timestamp;
Commentaar toegevoegd. Ook in domotica.h. De variabele representeert echt een timestamp (alleen niet tot op de seconde nauwkeurig), en niet een pattern.

2017-04-16 13:58 UTC, jmvdwerf commented on src/domotica/domotica_fastclock.c
> +    // If last_timestamp is smaller than the current_time, we just check
Aangepast. Als de waarde >= 2400, is het geen geldige klokwaarde en gaan we "gewoon" door...

2017-04-16 14:12 UTC, fuegas commented on src/domotica/domotica_fastclock.c
> +    if (timestamps[index].timestamp >= 2400)
Is dit een situatie waarvan we verwachten dat deze voor gaat komen? Want als dit in de CV waarden staat, dan hebben we eigenlijk corrupte data erin staan. Mijn gevoel zegt dat we dit bij het opstarten van de chip een keer willen controleren, maar niet bij elke tick die hier binnenkomt.

2017-04-16 14:12 UTC, fuegas commented on src/domotica/domotica_fastclock.c
> +        || // the rare case that last_timstamp > current_time. Then, it should
Niet heel relevant, maar er mist een `e` in `last_timstamp`.

2017-04-16 14:15 UTC, jmvdwerf commented on src/domotica/domotica_fastclock.c
> +    if (timestamps[index].timestamp >= 2400)
Op dit moment hebben we geen enabled/disabled LNCV per fast_clock entry. De enige manier om hem dus "snel" uit te zetten, is door de timestamp ongeldig te maken. Vandaar dat ik de controle in iedere tick doe...

2017-04-16 14:15 UTC, jmvdwerf commented on src/domotica/domotica_fastclock.c
> +        || // the rare case that last_timstamp > current_time. Then, it should
Repaired...

2017-04-16 14:22 UTC, fuegas commented on src/domotica/domotica_fastclock.c
> +    if (timestamps[index].timestamp >= 2400)
Na overleg besloten om de code te houden zoals in de PR geschreven.

2017-04-16 14:22 UTC, fuegas approved these changes

2017-04-16 14:22 UTC, merged