Feature/output change as ringbuffer
slashdev/loconet_domotica pull request #6
Opened 2017-02-17 15:12 UTC by jmvdwerf

Rewrote the linked list as a ringbuffer.

2017-02-23 13:47 UTC, fuegas requested changes

2017-02-23 13:47 UTC, fuegas commented on src/domotica/domotica.c
> +  (void) mask_on;
Deze voids mogen weg omdat je ze gebruikt in je functie.

2017-02-23 18:38 UTC, jmvdwerf commented on src/domotica/domotica.c
> +  (void) mask_on;
Changed!

2017-02-23 18:38 UTC, jmvdwerf commented
Consider it done!

2017-02-23 20:49 UTC, fuegas requested changes

2017-02-23 20:49 UTC, fuegas commented on src/domotica/domotica.c
> +} OUTPUT_CHANGE_RINGBUFFER_Type;
`OUTPUT_CHANGE_Type `, `DOMOTICA_CHANGE_BUFFER_Size` and `OUTPUT_CHANGE_RINGBUFFER_Type` are not consistent in naming.

2017-02-24 13:40 UTC, jmvdwerf commented on src/domotica/domotica.c
> +} OUTPUT_CHANGE_RINGBUFFER_Type;
Big reason is that the OUTPUT_CHANGE_ are internal variables that represent the buffer (and are static with a comprehensive name), whereas DOMOTICA_CHANGE_BUFFER_Size can be externally defined. For naming I found this more intuitive than having DOMOTICA_OUTPUT_CHANGE_... as a name...

2017-02-24 19:18 UTC, jmvdwerf commented
Changed!

2017-02-24 19:19 UTC, jmvdwerf commented on src/domotica/domotica.c
> +} OUTPUT_CHANGE_RINGBUFFER_Type;
I changed the names, as it only appears in the top part. Also the OUTPUT_CHANGE_Type needs to be exported for the next release to add priorities to it...

2017-02-24 19:27 UTC, fuegas requested changes

2017-02-24 19:27 UTC, fuegas commented on screen_layout
> +# the following two lines give a two-line status, with the current window highlighted
Please leave editor preferences out of the repository.

You can use them and keep them untracked by adding them to the global gitignore or the local ignore in `.git/info/exclude`.

2017-02-24 19:31 UTC, jmvdwerf commented on screen_layout
> +# the following two lines give a two-line status, with the current window highlighted
Deze zou eigenlijk in het hoofdproject geinclude moeten worden, maar dat is mijn persoonlijke mening...

2017-02-24 20:07 UTC, fuegas approved these changes

2017-02-24 20:09 UTC, merged